// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gona "github.com/netactuate/gona/gona"
	mock "github.com/stretchr/testify/mock"
)

// MockBGPSessionOperations is an autogenerated mock type for the BGPSessionOperations type
type MockBGPSessionOperations struct {
	mock.Mock
}

type MockBGPSessionOperations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBGPSessionOperations) EXPECT() *MockBGPSessionOperations_Expecter {
	return &MockBGPSessionOperations_Expecter{mock: &_m.Mock}
}

// CreateBGPSessions provides a mock function with given fields: ctx, mbPkgID, groupID, isIPV6, redundant
func (_m *MockBGPSessionOperations) CreateBGPSessions(ctx context.Context, mbPkgID int, groupID int, isIPV6 bool, redundant bool) (*gona.BGPSession, error) {
	ret := _m.Called(ctx, mbPkgID, groupID, isIPV6, redundant)

	if len(ret) == 0 {
		panic("no return value specified for CreateBGPSessions")
	}

	var r0 *gona.BGPSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, bool, bool) (*gona.BGPSession, error)); ok {
		return rf(ctx, mbPkgID, groupID, isIPV6, redundant)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, bool, bool) *gona.BGPSession); ok {
		r0 = rf(ctx, mbPkgID, groupID, isIPV6, redundant)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gona.BGPSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, bool, bool) error); ok {
		r1 = rf(ctx, mbPkgID, groupID, isIPV6, redundant)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBGPSessionOperations_CreateBGPSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBGPSessions'
type MockBGPSessionOperations_CreateBGPSessions_Call struct {
	*mock.Call
}

// CreateBGPSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - mbPkgID int
//   - groupID int
//   - isIPV6 bool
//   - redundant bool
func (_e *MockBGPSessionOperations_Expecter) CreateBGPSessions(ctx interface{}, mbPkgID interface{}, groupID interface{}, isIPV6 interface{}, redundant interface{}) *MockBGPSessionOperations_CreateBGPSessions_Call {
	return &MockBGPSessionOperations_CreateBGPSessions_Call{Call: _e.mock.On("CreateBGPSessions", ctx, mbPkgID, groupID, isIPV6, redundant)}
}

func (_c *MockBGPSessionOperations_CreateBGPSessions_Call) Run(run func(ctx context.Context, mbPkgID int, groupID int, isIPV6 bool, redundant bool)) *MockBGPSessionOperations_CreateBGPSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(bool), args[4].(bool))
	})
	return _c
}

func (_c *MockBGPSessionOperations_CreateBGPSessions_Call) Return(_a0 *gona.BGPSession, _a1 error) *MockBGPSessionOperations_CreateBGPSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBGPSessionOperations_CreateBGPSessions_Call) RunAndReturn(run func(context.Context, int, int, bool, bool) (*gona.BGPSession, error)) *MockBGPSessionOperations_CreateBGPSessions_Call {
	_c.Call.Return(run)
	return _c
}

// GetBGPSessions provides a mock function with given fields: ctx, mbPkgID
func (_m *MockBGPSessionOperations) GetBGPSessions(ctx context.Context, mbPkgID int) ([]*gona.BGPSession, error) {
	ret := _m.Called(ctx, mbPkgID)

	if len(ret) == 0 {
		panic("no return value specified for GetBGPSessions")
	}

	var r0 []*gona.BGPSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*gona.BGPSession, error)); ok {
		return rf(ctx, mbPkgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*gona.BGPSession); ok {
		r0 = rf(ctx, mbPkgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gona.BGPSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, mbPkgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBGPSessionOperations_GetBGPSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBGPSessions'
type MockBGPSessionOperations_GetBGPSessions_Call struct {
	*mock.Call
}

// GetBGPSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - mbPkgID int
func (_e *MockBGPSessionOperations_Expecter) GetBGPSessions(ctx interface{}, mbPkgID interface{}) *MockBGPSessionOperations_GetBGPSessions_Call {
	return &MockBGPSessionOperations_GetBGPSessions_Call{Call: _e.mock.On("GetBGPSessions", ctx, mbPkgID)}
}

func (_c *MockBGPSessionOperations_GetBGPSessions_Call) Run(run func(ctx context.Context, mbPkgID int)) *MockBGPSessionOperations_GetBGPSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockBGPSessionOperations_GetBGPSessions_Call) Return(_a0 []*gona.BGPSession, _a1 error) *MockBGPSessionOperations_GetBGPSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBGPSessionOperations_GetBGPSessions_Call) RunAndReturn(run func(context.Context, int) ([]*gona.BGPSession, error)) *MockBGPSessionOperations_GetBGPSessions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBGPSessionOperations creates a new instance of MockBGPSessionOperations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBGPSessionOperations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBGPSessionOperations {
	mock := &MockBGPSessionOperations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
