// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gona "github.com/netactuate/gona/gona"
	mock "github.com/stretchr/testify/mock"
)

// MockClientInterface is an autogenerated mock type for the ClientInterface type
type MockClientInterface struct {
	mock.Mock
}

type MockClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientInterface) EXPECT() *MockClientInterface_Expecter {
	return &MockClientInterface_Expecter{mock: &_m.Mock}
}

// BuildServer provides a mock function with given fields: _a0, id, r
func (_m *MockClientInterface) BuildServer(_a0 context.Context, id int, r *gona.BuildServerRequest) (gona.ServerBuild, error) {
	ret := _m.Called(_a0, id, r)

	if len(ret) == 0 {
		panic("no return value specified for BuildServer")
	}

	var r0 gona.ServerBuild
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *gona.BuildServerRequest) (gona.ServerBuild, error)); ok {
		return rf(_a0, id, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *gona.BuildServerRequest) gona.ServerBuild); ok {
		r0 = rf(_a0, id, r)
	} else {
		r0 = ret.Get(0).(gona.ServerBuild)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *gona.BuildServerRequest) error); ok {
		r1 = rf(_a0, id, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_BuildServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildServer'
type MockClientInterface_BuildServer_Call struct {
	*mock.Call
}

// BuildServer is a helper method to define mock.On call
//   - _a0 context.Context
//   - id int
//   - r *gona.BuildServerRequest
func (_e *MockClientInterface_Expecter) BuildServer(_a0 interface{}, id interface{}, r interface{}) *MockClientInterface_BuildServer_Call {
	return &MockClientInterface_BuildServer_Call{Call: _e.mock.On("BuildServer", _a0, id, r)}
}

func (_c *MockClientInterface_BuildServer_Call) Run(run func(_a0 context.Context, id int, r *gona.BuildServerRequest)) *MockClientInterface_BuildServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*gona.BuildServerRequest))
	})
	return _c
}

func (_c *MockClientInterface_BuildServer_Call) Return(_a0 gona.ServerBuild, _a1 error) *MockClientInterface_BuildServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_BuildServer_Call) RunAndReturn(run func(context.Context, int, *gona.BuildServerRequest) (gona.ServerBuild, error)) *MockClientInterface_BuildServer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBGPSessions provides a mock function with given fields: _a0, mbPkgID, groupID, isIPV6, redundant
func (_m *MockClientInterface) CreateBGPSessions(_a0 context.Context, mbPkgID int, groupID int, isIPV6 bool, redundant bool) (*gona.BGPSession, error) {
	ret := _m.Called(_a0, mbPkgID, groupID, isIPV6, redundant)

	if len(ret) == 0 {
		panic("no return value specified for CreateBGPSessions")
	}

	var r0 *gona.BGPSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, bool, bool) (*gona.BGPSession, error)); ok {
		return rf(_a0, mbPkgID, groupID, isIPV6, redundant)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, bool, bool) *gona.BGPSession); ok {
		r0 = rf(_a0, mbPkgID, groupID, isIPV6, redundant)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gona.BGPSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, bool, bool) error); ok {
		r1 = rf(_a0, mbPkgID, groupID, isIPV6, redundant)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_CreateBGPSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBGPSessions'
type MockClientInterface_CreateBGPSessions_Call struct {
	*mock.Call
}

// CreateBGPSessions is a helper method to define mock.On call
//   - _a0 context.Context
//   - mbPkgID int
//   - groupID int
//   - isIPV6 bool
//   - redundant bool
func (_e *MockClientInterface_Expecter) CreateBGPSessions(_a0 interface{}, mbPkgID interface{}, groupID interface{}, isIPV6 interface{}, redundant interface{}) *MockClientInterface_CreateBGPSessions_Call {
	return &MockClientInterface_CreateBGPSessions_Call{Call: _e.mock.On("CreateBGPSessions", _a0, mbPkgID, groupID, isIPV6, redundant)}
}

func (_c *MockClientInterface_CreateBGPSessions_Call) Run(run func(_a0 context.Context, mbPkgID int, groupID int, isIPV6 bool, redundant bool)) *MockClientInterface_CreateBGPSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(bool), args[4].(bool))
	})
	return _c
}

func (_c *MockClientInterface_CreateBGPSessions_Call) Return(_a0 *gona.BGPSession, _a1 error) *MockClientInterface_CreateBGPSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_CreateBGPSessions_Call) RunAndReturn(run func(context.Context, int, int, bool, bool) (*gona.BGPSession, error)) *MockClientInterface_CreateBGPSessions_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSSHKey provides a mock function with given fields: _a0, name, key
func (_m *MockClientInterface) CreateSSHKey(_a0 context.Context, name string, key string) (gona.SSHKey, error) {
	ret := _m.Called(_a0, name, key)

	if len(ret) == 0 {
		panic("no return value specified for CreateSSHKey")
	}

	var r0 gona.SSHKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (gona.SSHKey, error)); ok {
		return rf(_a0, name, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) gona.SSHKey); ok {
		r0 = rf(_a0, name, key)
	} else {
		r0 = ret.Get(0).(gona.SSHKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, name, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_CreateSSHKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSSHKey'
type MockClientInterface_CreateSSHKey_Call struct {
	*mock.Call
}

// CreateSSHKey is a helper method to define mock.On call
//   - _a0 context.Context
//   - name string
//   - key string
func (_e *MockClientInterface_Expecter) CreateSSHKey(_a0 interface{}, name interface{}, key interface{}) *MockClientInterface_CreateSSHKey_Call {
	return &MockClientInterface_CreateSSHKey_Call{Call: _e.mock.On("CreateSSHKey", _a0, name, key)}
}

func (_c *MockClientInterface_CreateSSHKey_Call) Run(run func(_a0 context.Context, name string, key string)) *MockClientInterface_CreateSSHKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClientInterface_CreateSSHKey_Call) Return(_a0 gona.SSHKey, _a1 error) *MockClientInterface_CreateSSHKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_CreateSSHKey_Call) RunAndReturn(run func(context.Context, string, string) (gona.SSHKey, error)) *MockClientInterface_CreateSSHKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateServer provides a mock function with given fields: _a0, _a1
func (_m *MockClientInterface) CreateServer(_a0 context.Context, _a1 *gona.CreateServerRequest) (gona.ServerBuild, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateServer")
	}

	var r0 gona.ServerBuild
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gona.CreateServerRequest) (gona.ServerBuild, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gona.CreateServerRequest) gona.ServerBuild); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(gona.ServerBuild)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gona.CreateServerRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_CreateServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateServer'
type MockClientInterface_CreateServer_Call struct {
	*mock.Call
}

// CreateServer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *gona.CreateServerRequest
func (_e *MockClientInterface_Expecter) CreateServer(_a0 interface{}, _a1 interface{}) *MockClientInterface_CreateServer_Call {
	return &MockClientInterface_CreateServer_Call{Call: _e.mock.On("CreateServer", _a0, _a1)}
}

func (_c *MockClientInterface_CreateServer_Call) Run(run func(_a0 context.Context, _a1 *gona.CreateServerRequest)) *MockClientInterface_CreateServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gona.CreateServerRequest))
	})
	return _c
}

func (_c *MockClientInterface_CreateServer_Call) Return(_a0 gona.ServerBuild, _a1 error) *MockClientInterface_CreateServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_CreateServer_Call) RunAndReturn(run func(context.Context, *gona.CreateServerRequest) (gona.ServerBuild, error)) *MockClientInterface_CreateServer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSSHKey provides a mock function with given fields: _a0, id
func (_m *MockClientInterface) DeleteSSHKey(_a0 context.Context, id int) error {
	ret := _m.Called(_a0, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSSHKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(_a0, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientInterface_DeleteSSHKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSSHKey'
type MockClientInterface_DeleteSSHKey_Call struct {
	*mock.Call
}

// DeleteSSHKey is a helper method to define mock.On call
//   - _a0 context.Context
//   - id int
func (_e *MockClientInterface_Expecter) DeleteSSHKey(_a0 interface{}, id interface{}) *MockClientInterface_DeleteSSHKey_Call {
	return &MockClientInterface_DeleteSSHKey_Call{Call: _e.mock.On("DeleteSSHKey", _a0, id)}
}

func (_c *MockClientInterface_DeleteSSHKey_Call) Run(run func(_a0 context.Context, id int)) *MockClientInterface_DeleteSSHKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockClientInterface_DeleteSSHKey_Call) Return(_a0 error) *MockClientInterface_DeleteSSHKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientInterface_DeleteSSHKey_Call) RunAndReturn(run func(context.Context, int) error) *MockClientInterface_DeleteSSHKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteServer provides a mock function with given fields: _a0, id, cancelBilling
func (_m *MockClientInterface) DeleteServer(_a0 context.Context, id int, cancelBilling bool) error {
	ret := _m.Called(_a0, id, cancelBilling)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, bool) error); ok {
		r0 = rf(_a0, id, cancelBilling)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientInterface_DeleteServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServer'
type MockClientInterface_DeleteServer_Call struct {
	*mock.Call
}

// DeleteServer is a helper method to define mock.On call
//   - _a0 context.Context
//   - id int
//   - cancelBilling bool
func (_e *MockClientInterface_Expecter) DeleteServer(_a0 interface{}, id interface{}, cancelBilling interface{}) *MockClientInterface_DeleteServer_Call {
	return &MockClientInterface_DeleteServer_Call{Call: _e.mock.On("DeleteServer", _a0, id, cancelBilling)}
}

func (_c *MockClientInterface_DeleteServer_Call) Run(run func(_a0 context.Context, id int, cancelBilling bool)) *MockClientInterface_DeleteServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(bool))
	})
	return _c
}

func (_c *MockClientInterface_DeleteServer_Call) Return(_a0 error) *MockClientInterface_DeleteServer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientInterface_DeleteServer_Call) RunAndReturn(run func(context.Context, int, bool) error) *MockClientInterface_DeleteServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetBGPSessions provides a mock function with given fields: _a0, mbPkgID
func (_m *MockClientInterface) GetBGPSessions(_a0 context.Context, mbPkgID int) ([]*gona.BGPSession, error) {
	ret := _m.Called(_a0, mbPkgID)

	if len(ret) == 0 {
		panic("no return value specified for GetBGPSessions")
	}

	var r0 []*gona.BGPSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*gona.BGPSession, error)); ok {
		return rf(_a0, mbPkgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*gona.BGPSession); ok {
		r0 = rf(_a0, mbPkgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gona.BGPSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(_a0, mbPkgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_GetBGPSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBGPSessions'
type MockClientInterface_GetBGPSessions_Call struct {
	*mock.Call
}

// GetBGPSessions is a helper method to define mock.On call
//   - _a0 context.Context
//   - mbPkgID int
func (_e *MockClientInterface_Expecter) GetBGPSessions(_a0 interface{}, mbPkgID interface{}) *MockClientInterface_GetBGPSessions_Call {
	return &MockClientInterface_GetBGPSessions_Call{Call: _e.mock.On("GetBGPSessions", _a0, mbPkgID)}
}

func (_c *MockClientInterface_GetBGPSessions_Call) Run(run func(_a0 context.Context, mbPkgID int)) *MockClientInterface_GetBGPSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockClientInterface_GetBGPSessions_Call) Return(_a0 []*gona.BGPSession, _a1 error) *MockClientInterface_GetBGPSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_GetBGPSessions_Call) RunAndReturn(run func(context.Context, int) ([]*gona.BGPSession, error)) *MockClientInterface_GetBGPSessions_Call {
	_c.Call.Return(run)
	return _c
}

// GetIPs provides a mock function with given fields: _a0, mbPkgID
func (_m *MockClientInterface) GetIPs(_a0 context.Context, mbPkgID int) (gona.IPs, error) {
	ret := _m.Called(_a0, mbPkgID)

	if len(ret) == 0 {
		panic("no return value specified for GetIPs")
	}

	var r0 gona.IPs
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (gona.IPs, error)); ok {
		return rf(_a0, mbPkgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) gona.IPs); ok {
		r0 = rf(_a0, mbPkgID)
	} else {
		r0 = ret.Get(0).(gona.IPs)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(_a0, mbPkgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_GetIPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIPs'
type MockClientInterface_GetIPs_Call struct {
	*mock.Call
}

// GetIPs is a helper method to define mock.On call
//   - _a0 context.Context
//   - mbPkgID int
func (_e *MockClientInterface_Expecter) GetIPs(_a0 interface{}, mbPkgID interface{}) *MockClientInterface_GetIPs_Call {
	return &MockClientInterface_GetIPs_Call{Call: _e.mock.On("GetIPs", _a0, mbPkgID)}
}

func (_c *MockClientInterface_GetIPs_Call) Run(run func(_a0 context.Context, mbPkgID int)) *MockClientInterface_GetIPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockClientInterface_GetIPs_Call) Return(_a0 gona.IPs, _a1 error) *MockClientInterface_GetIPs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_GetIPs_Call) RunAndReturn(run func(context.Context, int) (gona.IPs, error)) *MockClientInterface_GetIPs_Call {
	_c.Call.Return(run)
	return _c
}

// GetLocations provides a mock function with given fields: _a0
func (_m *MockClientInterface) GetLocations(_a0 context.Context) ([]gona.Location, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetLocations")
	}

	var r0 []gona.Location
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]gona.Location, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []gona.Location); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gona.Location)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_GetLocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocations'
type MockClientInterface_GetLocations_Call struct {
	*mock.Call
}

// GetLocations is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockClientInterface_Expecter) GetLocations(_a0 interface{}) *MockClientInterface_GetLocations_Call {
	return &MockClientInterface_GetLocations_Call{Call: _e.mock.On("GetLocations", _a0)}
}

func (_c *MockClientInterface_GetLocations_Call) Run(run func(_a0 context.Context)) *MockClientInterface_GetLocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClientInterface_GetLocations_Call) Return(_a0 []gona.Location, _a1 error) *MockClientInterface_GetLocations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_GetLocations_Call) RunAndReturn(run func(context.Context) ([]gona.Location, error)) *MockClientInterface_GetLocations_Call {
	_c.Call.Return(run)
	return _c
}

// GetOSs provides a mock function with given fields: _a0
func (_m *MockClientInterface) GetOSs(_a0 context.Context) ([]gona.OS, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetOSs")
	}

	var r0 []gona.OS
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]gona.OS, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []gona.OS); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gona.OS)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_GetOSs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOSs'
type MockClientInterface_GetOSs_Call struct {
	*mock.Call
}

// GetOSs is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockClientInterface_Expecter) GetOSs(_a0 interface{}) *MockClientInterface_GetOSs_Call {
	return &MockClientInterface_GetOSs_Call{Call: _e.mock.On("GetOSs", _a0)}
}

func (_c *MockClientInterface_GetOSs_Call) Run(run func(_a0 context.Context)) *MockClientInterface_GetOSs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClientInterface_GetOSs_Call) Return(_a0 []gona.OS, _a1 error) *MockClientInterface_GetOSs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_GetOSs_Call) RunAndReturn(run func(context.Context) ([]gona.OS, error)) *MockClientInterface_GetOSs_Call {
	_c.Call.Return(run)
	return _c
}

// GetSSHKey provides a mock function with given fields: _a0, id
func (_m *MockClientInterface) GetSSHKey(_a0 context.Context, id int) (gona.SSHKey, error) {
	ret := _m.Called(_a0, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSSHKey")
	}

	var r0 gona.SSHKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (gona.SSHKey, error)); ok {
		return rf(_a0, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) gona.SSHKey); ok {
		r0 = rf(_a0, id)
	} else {
		r0 = ret.Get(0).(gona.SSHKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(_a0, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_GetSSHKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSSHKey'
type MockClientInterface_GetSSHKey_Call struct {
	*mock.Call
}

// GetSSHKey is a helper method to define mock.On call
//   - _a0 context.Context
//   - id int
func (_e *MockClientInterface_Expecter) GetSSHKey(_a0 interface{}, id interface{}) *MockClientInterface_GetSSHKey_Call {
	return &MockClientInterface_GetSSHKey_Call{Call: _e.mock.On("GetSSHKey", _a0, id)}
}

func (_c *MockClientInterface_GetSSHKey_Call) Run(run func(_a0 context.Context, id int)) *MockClientInterface_GetSSHKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockClientInterface_GetSSHKey_Call) Return(_a0 gona.SSHKey, _a1 error) *MockClientInterface_GetSSHKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_GetSSHKey_Call) RunAndReturn(run func(context.Context, int) (gona.SSHKey, error)) *MockClientInterface_GetSSHKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetServer provides a mock function with given fields: _a0, id
func (_m *MockClientInterface) GetServer(_a0 context.Context, id int) (gona.Server, error) {
	ret := _m.Called(_a0, id)

	if len(ret) == 0 {
		panic("no return value specified for GetServer")
	}

	var r0 gona.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (gona.Server, error)); ok {
		return rf(_a0, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) gona.Server); ok {
		r0 = rf(_a0, id)
	} else {
		r0 = ret.Get(0).(gona.Server)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(_a0, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientInterface_GetServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServer'
type MockClientInterface_GetServer_Call struct {
	*mock.Call
}

// GetServer is a helper method to define mock.On call
//   - _a0 context.Context
//   - id int
func (_e *MockClientInterface_Expecter) GetServer(_a0 interface{}, id interface{}) *MockClientInterface_GetServer_Call {
	return &MockClientInterface_GetServer_Call{Call: _e.mock.On("GetServer", _a0, id)}
}

func (_c *MockClientInterface_GetServer_Call) Run(run func(_a0 context.Context, id int)) *MockClientInterface_GetServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockClientInterface_GetServer_Call) Return(_a0 gona.Server, _a1 error) *MockClientInterface_GetServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientInterface_GetServer_Call) RunAndReturn(run func(context.Context, int) (gona.Server, error)) *MockClientInterface_GetServer_Call {
	_c.Call.Return(run)
	return _c
}

// UnlinkServer provides a mock function with given fields: _a0, id
func (_m *MockClientInterface) UnlinkServer(_a0 context.Context, id int) error {
	ret := _m.Called(_a0, id)

	if len(ret) == 0 {
		panic("no return value specified for UnlinkServer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(_a0, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientInterface_UnlinkServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlinkServer'
type MockClientInterface_UnlinkServer_Call struct {
	*mock.Call
}

// UnlinkServer is a helper method to define mock.On call
//   - _a0 context.Context
//   - id int
func (_e *MockClientInterface_Expecter) UnlinkServer(_a0 interface{}, id interface{}) *MockClientInterface_UnlinkServer_Call {
	return &MockClientInterface_UnlinkServer_Call{Call: _e.mock.On("UnlinkServer", _a0, id)}
}

func (_c *MockClientInterface_UnlinkServer_Call) Run(run func(_a0 context.Context, id int)) *MockClientInterface_UnlinkServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockClientInterface_UnlinkServer_Call) Return(_a0 error) *MockClientInterface_UnlinkServer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientInterface_UnlinkServer_Call) RunAndReturn(run func(context.Context, int) error) *MockClientInterface_UnlinkServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientInterface creates a new instance of MockClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientInterface {
	mock := &MockClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
