// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gona "github.com/netactuate/gona/gona"
	mock "github.com/stretchr/testify/mock"
)

// MockIPOperations is an autogenerated mock type for the IPOperations type
type MockIPOperations struct {
	mock.Mock
}

type MockIPOperations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPOperations) EXPECT() *MockIPOperations_Expecter {
	return &MockIPOperations_Expecter{mock: &_m.Mock}
}

// GetIPs provides a mock function with given fields: ctx, mbPkgID
func (_m *MockIPOperations) GetIPs(ctx context.Context, mbPkgID int) (gona.IPs, error) {
	ret := _m.Called(ctx, mbPkgID)

	if len(ret) == 0 {
		panic("no return value specified for GetIPs")
	}

	var r0 gona.IPs
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (gona.IPs, error)); ok {
		return rf(ctx, mbPkgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) gona.IPs); ok {
		r0 = rf(ctx, mbPkgID)
	} else {
		r0 = ret.Get(0).(gona.IPs)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, mbPkgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPOperations_GetIPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIPs'
type MockIPOperations_GetIPs_Call struct {
	*mock.Call
}

// GetIPs is a helper method to define mock.On call
//   - ctx context.Context
//   - mbPkgID int
func (_e *MockIPOperations_Expecter) GetIPs(ctx interface{}, mbPkgID interface{}) *MockIPOperations_GetIPs_Call {
	return &MockIPOperations_GetIPs_Call{Call: _e.mock.On("GetIPs", ctx, mbPkgID)}
}

func (_c *MockIPOperations_GetIPs_Call) Run(run func(ctx context.Context, mbPkgID int)) *MockIPOperations_GetIPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIPOperations_GetIPs_Call) Return(_a0 gona.IPs, _a1 error) *MockIPOperations_GetIPs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPOperations_GetIPs_Call) RunAndReturn(run func(context.Context, int) (gona.IPs, error)) *MockIPOperations_GetIPs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPOperations creates a new instance of MockIPOperations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPOperations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPOperations {
	mock := &MockIPOperations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
