// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gona "github.com/netactuate/gona/gona"
	mock "github.com/stretchr/testify/mock"
)

// MockMetadataOperations is an autogenerated mock type for the MetadataOperations type
type MockMetadataOperations struct {
	mock.Mock
}

type MockMetadataOperations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataOperations) EXPECT() *MockMetadataOperations_Expecter {
	return &MockMetadataOperations_Expecter{mock: &_m.Mock}
}

// GetLocations provides a mock function with given fields: _a0
func (_m *MockMetadataOperations) GetLocations(_a0 context.Context) ([]gona.Location, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetLocations")
	}

	var r0 []gona.Location
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]gona.Location, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []gona.Location); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gona.Location)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetadataOperations_GetLocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocations'
type MockMetadataOperations_GetLocations_Call struct {
	*mock.Call
}

// GetLocations is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockMetadataOperations_Expecter) GetLocations(_a0 interface{}) *MockMetadataOperations_GetLocations_Call {
	return &MockMetadataOperations_GetLocations_Call{Call: _e.mock.On("GetLocations", _a0)}
}

func (_c *MockMetadataOperations_GetLocations_Call) Run(run func(_a0 context.Context)) *MockMetadataOperations_GetLocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMetadataOperations_GetLocations_Call) Return(_a0 []gona.Location, _a1 error) *MockMetadataOperations_GetLocations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetadataOperations_GetLocations_Call) RunAndReturn(run func(context.Context) ([]gona.Location, error)) *MockMetadataOperations_GetLocations_Call {
	_c.Call.Return(run)
	return _c
}

// GetOSs provides a mock function with given fields: _a0
func (_m *MockMetadataOperations) GetOSs(_a0 context.Context) ([]gona.OS, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetOSs")
	}

	var r0 []gona.OS
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]gona.OS, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []gona.OS); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gona.OS)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetadataOperations_GetOSs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOSs'
type MockMetadataOperations_GetOSs_Call struct {
	*mock.Call
}

// GetOSs is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockMetadataOperations_Expecter) GetOSs(_a0 interface{}) *MockMetadataOperations_GetOSs_Call {
	return &MockMetadataOperations_GetOSs_Call{Call: _e.mock.On("GetOSs", _a0)}
}

func (_c *MockMetadataOperations_GetOSs_Call) Run(run func(_a0 context.Context)) *MockMetadataOperations_GetOSs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMetadataOperations_GetOSs_Call) Return(_a0 []gona.OS, _a1 error) *MockMetadataOperations_GetOSs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetadataOperations_GetOSs_Call) RunAndReturn(run func(context.Context) ([]gona.OS, error)) *MockMetadataOperations_GetOSs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetadataOperations creates a new instance of MockMetadataOperations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataOperations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataOperations {
	mock := &MockMetadataOperations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
