// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gona "github.com/netactuate/gona/gona"
	mock "github.com/stretchr/testify/mock"
)

// MockServerOperations is an autogenerated mock type for the ServerOperations type
type MockServerOperations struct {
	mock.Mock
}

type MockServerOperations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerOperations) EXPECT() *MockServerOperations_Expecter {
	return &MockServerOperations_Expecter{mock: &_m.Mock}
}

// BuildServer provides a mock function with given fields: ctx, id, r
func (_m *MockServerOperations) BuildServer(ctx context.Context, id int, r *gona.BuildServerRequest) (gona.ServerBuild, error) {
	ret := _m.Called(ctx, id, r)

	if len(ret) == 0 {
		panic("no return value specified for BuildServer")
	}

	var r0 gona.ServerBuild
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *gona.BuildServerRequest) (gona.ServerBuild, error)); ok {
		return rf(ctx, id, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *gona.BuildServerRequest) gona.ServerBuild); ok {
		r0 = rf(ctx, id, r)
	} else {
		r0 = ret.Get(0).(gona.ServerBuild)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *gona.BuildServerRequest) error); ok {
		r1 = rf(ctx, id, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerOperations_BuildServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildServer'
type MockServerOperations_BuildServer_Call struct {
	*mock.Call
}

// BuildServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - r *gona.BuildServerRequest
func (_e *MockServerOperations_Expecter) BuildServer(ctx interface{}, id interface{}, r interface{}) *MockServerOperations_BuildServer_Call {
	return &MockServerOperations_BuildServer_Call{Call: _e.mock.On("BuildServer", ctx, id, r)}
}

func (_c *MockServerOperations_BuildServer_Call) Run(run func(ctx context.Context, id int, r *gona.BuildServerRequest)) *MockServerOperations_BuildServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*gona.BuildServerRequest))
	})
	return _c
}

func (_c *MockServerOperations_BuildServer_Call) Return(_a0 gona.ServerBuild, _a1 error) *MockServerOperations_BuildServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerOperations_BuildServer_Call) RunAndReturn(run func(context.Context, int, *gona.BuildServerRequest) (gona.ServerBuild, error)) *MockServerOperations_BuildServer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateServer provides a mock function with given fields: ctx, r
func (_m *MockServerOperations) CreateServer(ctx context.Context, r *gona.CreateServerRequest) (gona.ServerBuild, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateServer")
	}

	var r0 gona.ServerBuild
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gona.CreateServerRequest) (gona.ServerBuild, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gona.CreateServerRequest) gona.ServerBuild); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(gona.ServerBuild)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gona.CreateServerRequest) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerOperations_CreateServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateServer'
type MockServerOperations_CreateServer_Call struct {
	*mock.Call
}

// CreateServer is a helper method to define mock.On call
//   - ctx context.Context
//   - r *gona.CreateServerRequest
func (_e *MockServerOperations_Expecter) CreateServer(ctx interface{}, r interface{}) *MockServerOperations_CreateServer_Call {
	return &MockServerOperations_CreateServer_Call{Call: _e.mock.On("CreateServer", ctx, r)}
}

func (_c *MockServerOperations_CreateServer_Call) Run(run func(ctx context.Context, r *gona.CreateServerRequest)) *MockServerOperations_CreateServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gona.CreateServerRequest))
	})
	return _c
}

func (_c *MockServerOperations_CreateServer_Call) Return(_a0 gona.ServerBuild, _a1 error) *MockServerOperations_CreateServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerOperations_CreateServer_Call) RunAndReturn(run func(context.Context, *gona.CreateServerRequest) (gona.ServerBuild, error)) *MockServerOperations_CreateServer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteServer provides a mock function with given fields: ctx, id, cancelBilling
func (_m *MockServerOperations) DeleteServer(ctx context.Context, id int, cancelBilling bool) error {
	ret := _m.Called(ctx, id, cancelBilling)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, bool) error); ok {
		r0 = rf(ctx, id, cancelBilling)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerOperations_DeleteServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServer'
type MockServerOperations_DeleteServer_Call struct {
	*mock.Call
}

// DeleteServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - cancelBilling bool
func (_e *MockServerOperations_Expecter) DeleteServer(ctx interface{}, id interface{}, cancelBilling interface{}) *MockServerOperations_DeleteServer_Call {
	return &MockServerOperations_DeleteServer_Call{Call: _e.mock.On("DeleteServer", ctx, id, cancelBilling)}
}

func (_c *MockServerOperations_DeleteServer_Call) Run(run func(ctx context.Context, id int, cancelBilling bool)) *MockServerOperations_DeleteServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(bool))
	})
	return _c
}

func (_c *MockServerOperations_DeleteServer_Call) Return(_a0 error) *MockServerOperations_DeleteServer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerOperations_DeleteServer_Call) RunAndReturn(run func(context.Context, int, bool) error) *MockServerOperations_DeleteServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetServer provides a mock function with given fields: ctx, id
func (_m *MockServerOperations) GetServer(ctx context.Context, id int) (gona.Server, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetServer")
	}

	var r0 gona.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (gona.Server, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) gona.Server); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(gona.Server)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerOperations_GetServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServer'
type MockServerOperations_GetServer_Call struct {
	*mock.Call
}

// GetServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockServerOperations_Expecter) GetServer(ctx interface{}, id interface{}) *MockServerOperations_GetServer_Call {
	return &MockServerOperations_GetServer_Call{Call: _e.mock.On("GetServer", ctx, id)}
}

func (_c *MockServerOperations_GetServer_Call) Run(run func(ctx context.Context, id int)) *MockServerOperations_GetServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockServerOperations_GetServer_Call) Return(_a0 gona.Server, _a1 error) *MockServerOperations_GetServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerOperations_GetServer_Call) RunAndReturn(run func(context.Context, int) (gona.Server, error)) *MockServerOperations_GetServer_Call {
	_c.Call.Return(run)
	return _c
}

// UnlinkServer provides a mock function with given fields: ctx, id
func (_m *MockServerOperations) UnlinkServer(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UnlinkServer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerOperations_UnlinkServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlinkServer'
type MockServerOperations_UnlinkServer_Call struct {
	*mock.Call
}

// UnlinkServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockServerOperations_Expecter) UnlinkServer(ctx interface{}, id interface{}) *MockServerOperations_UnlinkServer_Call {
	return &MockServerOperations_UnlinkServer_Call{Call: _e.mock.On("UnlinkServer", ctx, id)}
}

func (_c *MockServerOperations_UnlinkServer_Call) Run(run func(ctx context.Context, id int)) *MockServerOperations_UnlinkServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockServerOperations_UnlinkServer_Call) Return(_a0 error) *MockServerOperations_UnlinkServer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerOperations_UnlinkServer_Call) RunAndReturn(run func(context.Context, int) error) *MockServerOperations_UnlinkServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerOperations creates a new instance of MockServerOperations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerOperations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerOperations {
	mock := &MockServerOperations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
