// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gona "github.com/netactuate/gona/gona"
	mock "github.com/stretchr/testify/mock"
)

// MockServerOperations is an autogenerated mock type for the ServerOperations type
type MockServerOperations struct {
	mock.Mock
}

type MockServerOperations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerOperations) EXPECT() *MockServerOperations_Expecter {
	return &MockServerOperations_Expecter{mock: &_m.Mock}
}

// BuildServer provides a mock function with given fields: _a0, id, r
func (_m *MockServerOperations) BuildServer(_a0 context.Context, id int, r *gona.BuildServerRequest) (gona.ServerBuild, error) {
	ret := _m.Called(_a0, id, r)

	if len(ret) == 0 {
		panic("no return value specified for BuildServer")
	}

	var r0 gona.ServerBuild
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *gona.BuildServerRequest) (gona.ServerBuild, error)); ok {
		return rf(_a0, id, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *gona.BuildServerRequest) gona.ServerBuild); ok {
		r0 = rf(_a0, id, r)
	} else {
		r0 = ret.Get(0).(gona.ServerBuild)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *gona.BuildServerRequest) error); ok {
		r1 = rf(_a0, id, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerOperations_BuildServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildServer'
type MockServerOperations_BuildServer_Call struct {
	*mock.Call
}

// BuildServer is a helper method to define mock.On call
//   - _a0 context.Context
//   - id int
//   - r *gona.BuildServerRequest
func (_e *MockServerOperations_Expecter) BuildServer(_a0 interface{}, id interface{}, r interface{}) *MockServerOperations_BuildServer_Call {
	return &MockServerOperations_BuildServer_Call{Call: _e.mock.On("BuildServer", _a0, id, r)}
}

func (_c *MockServerOperations_BuildServer_Call) Run(run func(_a0 context.Context, id int, r *gona.BuildServerRequest)) *MockServerOperations_BuildServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*gona.BuildServerRequest))
	})
	return _c
}

func (_c *MockServerOperations_BuildServer_Call) Return(_a0 gona.ServerBuild, _a1 error) *MockServerOperations_BuildServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerOperations_BuildServer_Call) RunAndReturn(run func(context.Context, int, *gona.BuildServerRequest) (gona.ServerBuild, error)) *MockServerOperations_BuildServer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateServer provides a mock function with given fields: _a0, _a1
func (_m *MockServerOperations) CreateServer(_a0 context.Context, _a1 *gona.CreateServerRequest) (gona.ServerBuild, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateServer")
	}

	var r0 gona.ServerBuild
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gona.CreateServerRequest) (gona.ServerBuild, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gona.CreateServerRequest) gona.ServerBuild); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(gona.ServerBuild)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gona.CreateServerRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerOperations_CreateServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateServer'
type MockServerOperations_CreateServer_Call struct {
	*mock.Call
}

// CreateServer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *gona.CreateServerRequest
func (_e *MockServerOperations_Expecter) CreateServer(_a0 interface{}, _a1 interface{}) *MockServerOperations_CreateServer_Call {
	return &MockServerOperations_CreateServer_Call{Call: _e.mock.On("CreateServer", _a0, _a1)}
}

func (_c *MockServerOperations_CreateServer_Call) Run(run func(_a0 context.Context, _a1 *gona.CreateServerRequest)) *MockServerOperations_CreateServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gona.CreateServerRequest))
	})
	return _c
}

func (_c *MockServerOperations_CreateServer_Call) Return(_a0 gona.ServerBuild, _a1 error) *MockServerOperations_CreateServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerOperations_CreateServer_Call) RunAndReturn(run func(context.Context, *gona.CreateServerRequest) (gona.ServerBuild, error)) *MockServerOperations_CreateServer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteServer provides a mock function with given fields: _a0, id, cancelBilling
func (_m *MockServerOperations) DeleteServer(_a0 context.Context, id int, cancelBilling bool) error {
	ret := _m.Called(_a0, id, cancelBilling)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, bool) error); ok {
		r0 = rf(_a0, id, cancelBilling)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerOperations_DeleteServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServer'
type MockServerOperations_DeleteServer_Call struct {
	*mock.Call
}

// DeleteServer is a helper method to define mock.On call
//   - _a0 context.Context
//   - id int
//   - cancelBilling bool
func (_e *MockServerOperations_Expecter) DeleteServer(_a0 interface{}, id interface{}, cancelBilling interface{}) *MockServerOperations_DeleteServer_Call {
	return &MockServerOperations_DeleteServer_Call{Call: _e.mock.On("DeleteServer", _a0, id, cancelBilling)}
}

func (_c *MockServerOperations_DeleteServer_Call) Run(run func(_a0 context.Context, id int, cancelBilling bool)) *MockServerOperations_DeleteServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(bool))
	})
	return _c
}

func (_c *MockServerOperations_DeleteServer_Call) Return(_a0 error) *MockServerOperations_DeleteServer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerOperations_DeleteServer_Call) RunAndReturn(run func(context.Context, int, bool) error) *MockServerOperations_DeleteServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetServer provides a mock function with given fields: _a0, id
func (_m *MockServerOperations) GetServer(_a0 context.Context, id int) (gona.Server, error) {
	ret := _m.Called(_a0, id)

	if len(ret) == 0 {
		panic("no return value specified for GetServer")
	}

	var r0 gona.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (gona.Server, error)); ok {
		return rf(_a0, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) gona.Server); ok {
		r0 = rf(_a0, id)
	} else {
		r0 = ret.Get(0).(gona.Server)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(_a0, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerOperations_GetServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServer'
type MockServerOperations_GetServer_Call struct {
	*mock.Call
}

// GetServer is a helper method to define mock.On call
//   - _a0 context.Context
//   - id int
func (_e *MockServerOperations_Expecter) GetServer(_a0 interface{}, id interface{}) *MockServerOperations_GetServer_Call {
	return &MockServerOperations_GetServer_Call{Call: _e.mock.On("GetServer", _a0, id)}
}

func (_c *MockServerOperations_GetServer_Call) Run(run func(_a0 context.Context, id int)) *MockServerOperations_GetServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockServerOperations_GetServer_Call) Return(_a0 gona.Server, _a1 error) *MockServerOperations_GetServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerOperations_GetServer_Call) RunAndReturn(run func(context.Context, int) (gona.Server, error)) *MockServerOperations_GetServer_Call {
	_c.Call.Return(run)
	return _c
}

// UnlinkServer provides a mock function with given fields: _a0, id
func (_m *MockServerOperations) UnlinkServer(_a0 context.Context, id int) error {
	ret := _m.Called(_a0, id)

	if len(ret) == 0 {
		panic("no return value specified for UnlinkServer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(_a0, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerOperations_UnlinkServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlinkServer'
type MockServerOperations_UnlinkServer_Call struct {
	*mock.Call
}

// UnlinkServer is a helper method to define mock.On call
//   - _a0 context.Context
//   - id int
func (_e *MockServerOperations_Expecter) UnlinkServer(_a0 interface{}, id interface{}) *MockServerOperations_UnlinkServer_Call {
	return &MockServerOperations_UnlinkServer_Call{Call: _e.mock.On("UnlinkServer", _a0, id)}
}

func (_c *MockServerOperations_UnlinkServer_Call) Run(run func(_a0 context.Context, id int)) *MockServerOperations_UnlinkServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockServerOperations_UnlinkServer_Call) Return(_a0 error) *MockServerOperations_UnlinkServer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerOperations_UnlinkServer_Call) RunAndReturn(run func(context.Context, int) error) *MockServerOperations_UnlinkServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerOperations creates a new instance of MockServerOperations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerOperations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerOperations {
	mock := &MockServerOperations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
