// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gona "github.com/netactuate/gona/gona"
	mock "github.com/stretchr/testify/mock"
)

// MockSSHKeyOperations is an autogenerated mock type for the SSHKeyOperations type
type MockSSHKeyOperations struct {
	mock.Mock
}

type MockSSHKeyOperations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSSHKeyOperations) EXPECT() *MockSSHKeyOperations_Expecter {
	return &MockSSHKeyOperations_Expecter{mock: &_m.Mock}
}

// CreateSSHKey provides a mock function with given fields: ctx, name, key
func (_m *MockSSHKeyOperations) CreateSSHKey(ctx context.Context, name string, key string) (gona.SSHKey, error) {
	ret := _m.Called(ctx, name, key)

	if len(ret) == 0 {
		panic("no return value specified for CreateSSHKey")
	}

	var r0 gona.SSHKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (gona.SSHKey, error)); ok {
		return rf(ctx, name, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) gona.SSHKey); ok {
		r0 = rf(ctx, name, key)
	} else {
		r0 = ret.Get(0).(gona.SSHKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSSHKeyOperations_CreateSSHKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSSHKey'
type MockSSHKeyOperations_CreateSSHKey_Call struct {
	*mock.Call
}

// CreateSSHKey is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - key string
func (_e *MockSSHKeyOperations_Expecter) CreateSSHKey(ctx interface{}, name interface{}, key interface{}) *MockSSHKeyOperations_CreateSSHKey_Call {
	return &MockSSHKeyOperations_CreateSSHKey_Call{Call: _e.mock.On("CreateSSHKey", ctx, name, key)}
}

func (_c *MockSSHKeyOperations_CreateSSHKey_Call) Run(run func(ctx context.Context, name string, key string)) *MockSSHKeyOperations_CreateSSHKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSSHKeyOperations_CreateSSHKey_Call) Return(_a0 gona.SSHKey, _a1 error) *MockSSHKeyOperations_CreateSSHKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSSHKeyOperations_CreateSSHKey_Call) RunAndReturn(run func(context.Context, string, string) (gona.SSHKey, error)) *MockSSHKeyOperations_CreateSSHKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSSHKey provides a mock function with given fields: ctx, id
func (_m *MockSSHKeyOperations) DeleteSSHKey(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSSHKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSSHKeyOperations_DeleteSSHKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSSHKey'
type MockSSHKeyOperations_DeleteSSHKey_Call struct {
	*mock.Call
}

// DeleteSSHKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockSSHKeyOperations_Expecter) DeleteSSHKey(ctx interface{}, id interface{}) *MockSSHKeyOperations_DeleteSSHKey_Call {
	return &MockSSHKeyOperations_DeleteSSHKey_Call{Call: _e.mock.On("DeleteSSHKey", ctx, id)}
}

func (_c *MockSSHKeyOperations_DeleteSSHKey_Call) Run(run func(ctx context.Context, id int)) *MockSSHKeyOperations_DeleteSSHKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSSHKeyOperations_DeleteSSHKey_Call) Return(_a0 error) *MockSSHKeyOperations_DeleteSSHKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSSHKeyOperations_DeleteSSHKey_Call) RunAndReturn(run func(context.Context, int) error) *MockSSHKeyOperations_DeleteSSHKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetSSHKey provides a mock function with given fields: ctx, id
func (_m *MockSSHKeyOperations) GetSSHKey(ctx context.Context, id int) (gona.SSHKey, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSSHKey")
	}

	var r0 gona.SSHKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (gona.SSHKey, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) gona.SSHKey); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(gona.SSHKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSSHKeyOperations_GetSSHKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSSHKey'
type MockSSHKeyOperations_GetSSHKey_Call struct {
	*mock.Call
}

// GetSSHKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockSSHKeyOperations_Expecter) GetSSHKey(ctx interface{}, id interface{}) *MockSSHKeyOperations_GetSSHKey_Call {
	return &MockSSHKeyOperations_GetSSHKey_Call{Call: _e.mock.On("GetSSHKey", ctx, id)}
}

func (_c *MockSSHKeyOperations_GetSSHKey_Call) Run(run func(ctx context.Context, id int)) *MockSSHKeyOperations_GetSSHKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSSHKeyOperations_GetSSHKey_Call) Return(_a0 gona.SSHKey, _a1 error) *MockSSHKeyOperations_GetSSHKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSSHKeyOperations_GetSSHKey_Call) RunAndReturn(run func(context.Context, int) (gona.SSHKey, error)) *MockSSHKeyOperations_GetSSHKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSSHKeyOperations creates a new instance of MockSSHKeyOperations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSSHKeyOperations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSSHKeyOperations {
	mock := &MockSSHKeyOperations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
